# Copy for every locale of the Rowhni landing page.
#
# House rules, applied in each language:
#   - no marketing buzzwords, no superlatives, no invented figures
#   - no em dashes
#   - say what the app does, in the plainest words the language allows
#
# Keep the keys identical across locales. build.py fails loudly on a missing
# one rather than silently shipping English into another language.

LOCALES = ["en", "de", "fr", "es", "tr", "ar", "ja", "id", "ms"]

LANG_NAMES = {
    "en": "English",
    "de": "Deutsch",
    "fr": "Français",
    "es": "Español",
    "tr": "Türkçe",
    "ar": "العربية",
    "ja": "日本語",
    "id": "Indonesia",
    "ms": "Melayu",
}

RTL = {"ar"}

S = {}

S["en"] = {
    "title": "Rowhni: prayer times, tasbih and Quran progress for iOS and Android",
    "description": "Rowhni calculates the five daily prayers on your device, counts dhikr by listening, tracks your place in the Quran, finds mosques nearby and works out zakat. Free on iOS and Android.",
    "og_title": "Rowhni: prayer times calculated on your phone",
    "og_description": "The five daily prayers, worked out on your device from your location. Plus voice tasbih, Quran progress, mosques nearby and a zakat calculator.",
    "skip": "Skip to content",
    "nav_label": "Main",
    "nav_features": "Features",
    "nav_privacy": "Privacy",
    "nav_support": "Support",
    "theme_label": "Colour theme",
    "theme_system": "Match system theme",
    "theme_light": "Light theme",
    "theme_dark": "Dark theme",
    "get_app": "Get the app",
    "menu_open": "Open menu",
    "menu_close": "Close",
    "h1": "Prayer times, calculated on your phone.",
    "lede": "Rowhni works out the five daily prayers from where you are, and does the calculation on your device. It also counts dhikr by listening, keeps your place in the Quran, finds mosques nearby and calculates zakat.",
    "note": "Free. Requires iOS 18 or later, or Android.",
    "store_download_on": "Download on the",
    "store_get_it_on": "Get it on",
    "times_caption": "Today's prayer times for the selected city",
    "th_prayer": "Prayer",
    "th_time": "Time",
    "next": "Next",
    "p_fajr": "Fajr",
    "p_sunrise": "Sunrise",
    "p_dhuhr": "Dhuhr",
    "p_asr": "Asr",
    "p_maghrib": "Maghrib",
    "p_isha": "Isha",
    "city": "City",
    "method": "Method",
    "proof": "Your browser calculated these times from the city's coordinates using the same astronomical method the app uses. Nothing was sent to a server.",
    "noscript": "Times need JavaScript to be calculated. Everything else on this page works without it.",
    "features_h2": "What it does",
    "f1_h3": "The five prayers, and the sun behind them",
    "f1_p": "Times are computed from your coordinates using standard solar geometry, so they hold wherever you are. A sun path shows the whole day at a glance, and a Live Activity puts the countdown to the next prayer on your lock screen.",
    "f1_li1": "Several calculation conventions, so it can match your mosque",
    "f1_li2": "Adhan notifications you can set per prayer",
    "f1_li3": "Qibla direction from your position",
    "f1_alt": "The prayer times screen for Mecca, with Fajr as the next prayer, a countdown to it, and today's times below.",
    "f2_h3": "A tasbih that listens",
    "f2_p": "Say the dhikr and the counter follows. It recognises the phrases in Arabic and in transliteration, so you can keep your hands and your eyes off the phone. Tapping still works when speaking does not suit the room.",
    "f2_li1": "Voice counting is optional; tapping always works",
    "f2_li2": "Targets for each dhikr, with the day's history kept",
    "f2_alt": "The tasbih screen showing Subhanallah in Arabic with its translation, and a ring of beads around a counter set to a target of 33.",
    "f3_h3": "Your place in the Quran, kept",
    "f3_p": "Progress is tracked by juz, surah and ayah, so picking up where you stopped does not depend on remembering. Translations and recitations sit alongside the text.",
    "f3_alt": "Surah Al-Fatihah, with the Arabic text colour-coded for tajwid, an English translation and a transliteration under each verse.",
    "f4_h3": "Mosques near you",
    "f4_p": "A map of the mosques around your position, searchable by name, for the times you are somewhere unfamiliar and need to find jama'ah.",
    "f4_alt": "A map of Mecca with thirty nearby mosques marked, and a search field above it.",
    "f5_h3": "Zakat, worked out step by step",
    "f5_p": "The nisab threshold in gold and in silver, updated with current metal prices, and separate entries for cash, gold, silver, business assets and livestock.",
    "f5_alt": "The zakat calculator showing the gold and silver nisab thresholds, with categories for cash and savings, gold, silver and business assets.",
    "f6_h3": "An encyclopedia to read through",
    "f6_p": "The prophets and their stories, a hadith collection, and a quiz to test what stuck. Written to be read, not skimmed.",
    "f6_alt": "The encyclopedia index, listing the Five Pillars, Aqidah, Fiqh, Guidance, the Prophets and the Seerah.",
    "priv_h2": "What leaves your phone",
    "priv_lead": "Short answer: your location does not. The longer answer is in the {privacy_link}, which is written to be read rather than agreed to.",
    "priv_link_text": "privacy policy",
    "fact1_dt": "Location",
    "fact1_dd": "Used on the device to compute times and the qibla. Once a month the app checks the coordinates against an official prayer-time service to match local convention, and asks Apple to name your city.",
    "fact2_dt": "Voice",
    "fact2_dd": "Dhikr recognition uses Apple's speech recognition, which sends audio to Apple to be transcribed. It only runs while you hold the voice button.",
    "fact3_dt": "This website",
    "fact3_dd": "No cookies, no analytics, no third-party requests. Fonts are served from this domain.",
    "fact4_dt": "Your account",
    "fact4_dd": "You can {delete_link} without writing to anyone.",
    "fact4_link_text": "delete it and its data",
    "cta_h2": "Try it for the next prayer",
    "cta_p": "Free on both stores. If it does not suit how you pray, delete it; nothing is kept on our side either way.",
    "foot_tagline": "An Islamic companion app for iOS and Android, made by Harun Yaman.",
    "foot_app": "App",
    "foot_help": "Help",
    "foot_legal": "Legal",
    "foot_contact": "Contact",
    "foot_delete": "Delete account",
    "legal_privacy": "Privacy policy",
    "legal_choices": "Privacy choices",
    "legal_terms": "Terms",
    "legal_licences": "Open-source licences",
    "lang_label": "Language",
}

S["de"] = {
    "title": "Rowhni: Gebetszeiten, Tasbih und Koran-Fortschritt für iOS und Android",
    "description": "Rowhni berechnet die fünf täglichen Gebete auf deinem Gerät, zählt Dhikr per Stimme, merkt sich deine Stelle im Koran, findet Moscheen in der Nähe und berechnet die Zakat. Kostenlos für iOS und Android.",
    "og_title": "Rowhni: Gebetszeiten, auf deinem Telefon berechnet",
    "og_description": "Die fünf täglichen Gebete, auf deinem Gerät aus deinem Standort berechnet. Dazu Tasbih per Stimme, Koran-Fortschritt, Moscheen in der Nähe und ein Zakat-Rechner.",
    "skip": "Zum Inhalt springen",
    "nav_label": "Hauptnavigation",
    "nav_features": "Funktionen",
    "nav_privacy": "Datenschutz",
    "nav_support": "Hilfe",
    "theme_label": "Farbschema",
    "theme_system": "Systemeinstellung übernehmen",
    "theme_light": "Helles Schema",
    "theme_dark": "Dunkles Schema",
    "get_app": "App laden",
    "menu_open": "Menü öffnen",
    "menu_close": "Schließen",
    "h1": "Gebetszeiten, auf deinem Telefon berechnet.",
    "lede": "Rowhni ermittelt die fünf täglichen Gebete aus deinem Standort und rechnet dabei auf deinem Gerät. Die App zählt außerdem Dhikr per Stimme, merkt sich deine Stelle im Koran, findet Moscheen in der Nähe und berechnet die Zakat.",
    "note": "Kostenlos. Erfordert iOS 18 oder neuer, oder Android.",
    "store_download_on": "Laden im",
    "store_get_it_on": "Jetzt bei",
    "times_caption": "Heutige Gebetszeiten für die gewählte Stadt",
    "th_prayer": "Gebet",
    "th_time": "Uhrzeit",
    "next": "Nächstes",
    "p_fajr": "Fadschr",
    "p_sunrise": "Sonnenaufgang",
    "p_dhuhr": "Dhuhr",
    "p_asr": "Asr",
    "p_maghrib": "Maghrib",
    "p_isha": "Ischa",
    "city": "Stadt",
    "method": "Methode",
    "proof": "Dein Browser hat diese Zeiten aus den Koordinaten der Stadt berechnet, mit derselben astronomischen Methode wie die App. Es wurde nichts an einen Server gesendet.",
    "noscript": "Für die Berechnung der Zeiten wird JavaScript benötigt. Alles andere auf dieser Seite funktioniert auch ohne.",
    "features_h2": "Was die App macht",
    "f1_h3": "Die fünf Gebete und der Sonnenstand dahinter",
    "f1_p": "Die Zeiten werden aus deinen Koordinaten mit den üblichen astronomischen Formeln berechnet und stimmen deshalb überall. Eine Sonnenbahn zeigt den ganzen Tag auf einen Blick, und eine Live-Aktivität bringt die Zeit bis zum nächsten Gebet auf den Sperrbildschirm.",
    "f1_li1": "Mehrere Berechnungsmethoden, passend zu deiner Moschee",
    "f1_li2": "Adhan-Benachrichtigungen, je Gebet einstellbar",
    "f1_li3": "Qibla-Richtung von deinem Standort aus",
    "f1_alt": "Der Gebetszeiten-Bildschirm für Mekka: Fadschr als nächstes Gebet, die Zeit bis dahin und darunter die heutigen Zeiten.",
    "f2_h3": "Ein Tasbih, das zuhört",
    "f2_p": "Sprich den Dhikr, der Zähler folgt. Die App erkennt die Formeln auf Arabisch und in Umschrift, sodass Hände und Augen frei bleiben. Tippen funktioniert weiterhin, wenn Sprechen gerade nicht passt.",
    "f2_li1": "Das Zählen per Stimme ist optional, Tippen geht immer",
    "f2_li2": "Ziele je Dhikr, mit dem Verlauf des Tages",
    "f2_alt": "Der Tasbih-Bildschirm zeigt Subhanallah auf Arabisch mit Übersetzung und einen Perlenkranz um einen Zähler mit dem Ziel 33.",
    "f3_h3": "Deine Stelle im Koran, gemerkt",
    "f3_p": "Der Fortschritt wird nach Dschuz, Sure und Aya festgehalten. Weiterlesen hängt damit nicht mehr am Erinnern. Übersetzungen und Rezitationen stehen direkt beim Text.",
    "f3_alt": "Sure Al-Fatiha mit arabischem Text in Tadschwid-Farben, englischer Übersetzung und Umschrift unter jedem Vers.",
    "f4_h3": "Moscheen in deiner Nähe",
    "f4_p": "Eine Karte der Moscheen rund um deinen Standort, nach Namen durchsuchbar, für die Tage, an denen du unterwegs bist und ein Gemeinschaftsgebet suchst.",
    "f4_alt": "Eine Karte von Mekka mit dreißig markierten Moscheen in der Nähe und einem Suchfeld darüber.",
    "f5_h3": "Zakat, Schritt für Schritt gerechnet",
    "f5_p": "Der Nisab-Schwellenwert in Gold und in Silber, mit aktuellen Metallpreisen, dazu getrennte Posten für Bargeld, Gold, Silber, Betriebsvermögen und Vieh.",
    "f5_alt": "Der Zakat-Rechner mit den Nisab-Schwellen für Gold und Silber sowie Kategorien für Bargeld und Ersparnisse, Gold, Silber und Betriebsvermögen.",
    "f6_h3": "Ein Nachschlagewerk zum Lesen",
    "f6_p": "Die Propheten und ihre Geschichten, eine Hadith-Sammlung und ein Quiz, das prüft, was hängen geblieben ist. Zum Lesen geschrieben, nicht zum Überfliegen.",
    "f6_alt": "Das Inhaltsverzeichnis des Nachschlagewerks mit den fünf Säulen, Aqida, Fiqh, Wegweisung, den Propheten und der Sira.",
    "priv_h2": "Was dein Telefon verlässt",
    "priv_lead": "Kurz gesagt: dein Standort nicht. Die ausführliche Antwort steht in der {privacy_link}, die zum Lesen geschrieben ist und nicht zum Abnicken.",
    "priv_link_text": "Datenschutzerklärung",
    "fact1_dt": "Standort",
    "fact1_dd": "Wird auf dem Gerät für Zeiten und Qibla verwendet. Einmal im Monat gleicht die App die Koordinaten mit einem offiziellen Zeitendienst ab, um der örtlichen Konvention zu folgen, und lässt sich von Apple den Städtenamen geben.",
    "fact2_dt": "Stimme",
    "fact2_dd": "Die Dhikr-Erkennung nutzt Apples Spracherkennung und sendet dafür Audio zur Umschrift an Apple. Sie läuft nur, solange du die Sprachtaste hältst.",
    "fact3_dt": "Diese Website",
    "fact3_dd": "Keine Cookies, keine Analyse, keine Anfragen an Dritte. Die Schriften kommen von dieser Domain.",
    "fact4_dt": "Dein Konto",
    "fact4_dd": "Du kannst es {delete_link}, ohne jemandem zu schreiben.",
    "fact4_link_text": "samt Daten löschen",
    "cta_h2": "Probier es beim nächsten Gebet",
    "cta_p": "In beiden Stores kostenlos. Wenn es nicht zu deiner Praxis passt, lösch es wieder; bei uns bleibt so oder so nichts liegen.",
    "foot_tagline": "Eine islamische Begleit-App für iOS und Android, entwickelt von Harun Yaman.",
    "foot_app": "App",
    "foot_help": "Hilfe",
    "foot_legal": "Rechtliches",
    "foot_contact": "Kontakt",
    "foot_delete": "Konto löschen",
    "legal_privacy": "Datenschutz",
    "legal_choices": "Datenschutz-Optionen",
    "legal_terms": "Nutzungsbedingungen",
    "legal_licences": "Open-Source-Lizenzen",
    "lang_label": "Sprache",
}

S["fr"] = {
    "title": "Rowhni : heures de prière, tasbih et progression dans le Coran pour iOS et Android",
    "description": "Rowhni calcule les cinq prières quotidiennes sur votre appareil, compte le dhikr à la voix, retient votre place dans le Coran, trouve les mosquées à proximité et calcule la zakat. Gratuit sur iOS et Android.",
    "og_title": "Rowhni : les heures de prière calculées sur votre téléphone",
    "og_description": "Les cinq prières quotidiennes, calculées sur votre appareil à partir de votre position. Avec le tasbih vocal, la progression dans le Coran, les mosquées proches et un calculateur de zakat.",
    "skip": "Aller au contenu",
    "nav_label": "Navigation principale",
    "nav_features": "Fonctions",
    "nav_privacy": "Confidentialité",
    "nav_support": "Aide",
    "theme_label": "Thème de couleur",
    "theme_system": "Suivre le système",
    "theme_light": "Thème clair",
    "theme_dark": "Thème sombre",
    "get_app": "Obtenir l'app",
    "menu_open": "Ouvrir le menu",
    "menu_close": "Fermer",
    "h1": "Les heures de prière, calculées sur votre téléphone.",
    "lede": "Rowhni établit les cinq prières quotidiennes à partir de votre position, et fait le calcul sur votre appareil. L'app compte aussi le dhikr à la voix, retient votre place dans le Coran, trouve les mosquées proches et calcule la zakat.",
    "note": "Gratuit. Nécessite iOS 18 ou plus récent, ou Android.",
    "store_download_on": "Télécharger dans l'",
    "store_get_it_on": "Disponible sur",
    "times_caption": "Heures de prière du jour pour la ville choisie",
    "th_prayer": "Prière",
    "th_time": "Heure",
    "next": "Prochaine",
    "p_fajr": "Fajr",
    "p_sunrise": "Lever du soleil",
    "p_dhuhr": "Dhuhr",
    "p_asr": "Asr",
    "p_maghrib": "Maghrib",
    "p_isha": "Isha",
    "city": "Ville",
    "method": "Méthode",
    "proof": "Votre navigateur a calculé ces heures à partir des coordonnées de la ville, avec la même méthode astronomique que l'app. Rien n'a été envoyé à un serveur.",
    "noscript": "Le calcul des heures demande JavaScript. Tout le reste de cette page fonctionne sans.",
    "features_h2": "Ce que fait l'app",
    "f1_h3": "Les cinq prières, et la course du soleil derrière",
    "f1_p": "Les heures sont calculées à partir de vos coordonnées avec la géométrie solaire habituelle : elles tiennent donc partout. Une courbe montre la journée entière d'un coup d'œil, et une activité en direct affiche le compte à rebours sur l'écran verrouillé.",
    "f1_li1": "Plusieurs conventions de calcul, pour s'accorder à votre mosquée",
    "f1_li2": "Notifications d'adhan, réglables prière par prière",
    "f1_li3": "Direction de la qibla depuis votre position",
    "f1_alt": "L'écran des heures de prière pour La Mecque : Fajr comme prochaine prière, le temps restant, et les heures du jour en dessous.",
    "f2_h3": "Un tasbih qui écoute",
    "f2_p": "Dites le dhikr, le compteur suit. L'app reconnaît les formules en arabe et en translittération, ce qui laisse les mains et les yeux libres. Le comptage tactile reste disponible quand parler ne convient pas.",
    "f2_li1": "Le comptage vocal est optionnel, le tactile fonctionne toujours",
    "f2_li2": "Un objectif par dhikr, avec l'historique du jour",
    "f2_alt": "L'écran du tasbih affichant Subhanallah en arabe avec sa traduction, et un chapelet autour d'un compteur réglé sur 33.",
    "f3_h3": "Votre place dans le Coran, retenue",
    "f3_p": "La progression est suivie par juz, sourate et verset : reprendre ne dépend plus de votre mémoire. Traductions et récitations accompagnent le texte.",
    "f3_alt": "La sourate Al-Fatiha, texte arabe coloré selon le tajwid, traduction anglaise et translittération sous chaque verset.",
    "f4_h3": "Les mosquées près de vous",
    "f4_p": "Une carte des mosquées autour de votre position, avec recherche par nom, pour les jours où vous êtes en déplacement et cherchez la prière en commun.",
    "f4_alt": "Une carte de La Mecque avec trente mosquées proches signalées, et un champ de recherche au-dessus.",
    "f5_h3": "La zakat, calculée pas à pas",
    "f5_p": "Le seuil du nisab en or et en argent, mis à jour avec les cours des métaux, et des postes distincts pour les liquidités, l'or, l'argent, les actifs professionnels et le bétail.",
    "f5_alt": "Le calculateur de zakat montrant les seuils de nisab en or et en argent, avec les catégories liquidités et épargne, or, argent et actifs professionnels.",
    "f6_h3": "Une encyclopédie à lire",
    "f6_p": "Les prophètes et leurs récits, un recueil de hadiths, et un quiz pour vérifier ce qui est resté. Écrite pour être lue, pas parcourue.",
    "f6_alt": "Le sommaire de l'encyclopédie : les cinq piliers, l'aqida, le fiqh, la guidance, les prophètes et la sira.",
    "priv_h2": "Ce qui quitte votre téléphone",
    "priv_lead": "Réponse courte : pas votre position. La réponse longue est dans la {privacy_link}, écrite pour être lue et non pour être acceptée d'un clic.",
    "priv_link_text": "politique de confidentialité",
    "fact1_dt": "Position",
    "fact1_dd": "Utilisée sur l'appareil pour les heures et la qibla. Une fois par mois, l'app compare les coordonnées à un service officiel d'heures de prière pour suivre l'usage local, et demande à Apple le nom de votre ville.",
    "fact2_dt": "Voix",
    "fact2_dd": "La reconnaissance du dhikr passe par la reconnaissance vocale d'Apple, qui envoie l'audio à Apple pour transcription. Elle ne tourne que pendant que vous maintenez le bouton vocal.",
    "fact3_dt": "Ce site",
    "fact3_dd": "Pas de cookies, pas de mesure d'audience, aucune requête vers un tiers. Les polices viennent de ce domaine.",
    "fact4_dt": "Votre compte",
    "fact4_dd": "Vous pouvez {delete_link} sans écrire à personne.",
    "fact4_link_text": "le supprimer avec ses données",
    "cta_h2": "Essayez-la à la prochaine prière",
    "cta_p": "Gratuite sur les deux boutiques. Si elle ne convient pas à votre pratique, supprimez-la ; de notre côté, rien n'est conservé dans un cas comme dans l'autre.",
    "foot_tagline": "Une app de compagnie islamique pour iOS et Android, réalisée par Harun Yaman.",
    "foot_app": "App",
    "foot_help": "Aide",
    "foot_legal": "Mentions légales",
    "foot_contact": "Contact",
    "foot_delete": "Supprimer le compte",
    "legal_privacy": "Confidentialité",
    "legal_choices": "Choix de confidentialité",
    "legal_terms": "Conditions",
    "legal_licences": "Licences open source",
    "lang_label": "Langue",
}

S["es"] = {
    "title": "Rowhni: horarios de oración, tasbih y progreso en el Corán para iOS y Android",
    "description": "Rowhni calcula las cinco oraciones diarias en tu dispositivo, cuenta el dhikr por voz, guarda tu lugar en el Corán, encuentra mezquitas cercanas y calcula el zakat. Gratis en iOS y Android.",
    "og_title": "Rowhni: horarios de oración calculados en tu teléfono",
    "og_description": "Las cinco oraciones diarias, calculadas en tu dispositivo a partir de tu ubicación. Además tasbih por voz, progreso en el Corán, mezquitas cercanas y calculadora de zakat.",
    "skip": "Ir al contenido",
    "nav_label": "Navegación principal",
    "nav_features": "Funciones",
    "nav_privacy": "Privacidad",
    "nav_support": "Ayuda",
    "theme_label": "Tema de color",
    "theme_system": "Seguir el sistema",
    "theme_light": "Tema claro",
    "theme_dark": "Tema oscuro",
    "get_app": "Descargar la app",
    "menu_open": "Abrir menú",
    "menu_close": "Cerrar",
    "h1": "Horarios de oración, calculados en tu teléfono.",
    "lede": "Rowhni deduce las cinco oraciones diarias a partir de dónde estás y hace el cálculo en tu dispositivo. También cuenta el dhikr por voz, guarda tu lugar en el Corán, encuentra mezquitas cercanas y calcula el zakat.",
    "note": "Gratis. Requiere iOS 18 o posterior, o Android.",
    "store_download_on": "Descárgala en el",
    "store_get_it_on": "Disponible en",
    "times_caption": "Horarios de oración de hoy para la ciudad elegida",
    "th_prayer": "Oración",
    "th_time": "Hora",
    "next": "Siguiente",
    "p_fajr": "Fayr",
    "p_sunrise": "Amanecer",
    "p_dhuhr": "Duhr",
    "p_asr": "Asr",
    "p_maghrib": "Magrib",
    "p_isha": "Isha",
    "city": "Ciudad",
    "method": "Método",
    "proof": "Tu navegador calculó estos horarios con las coordenadas de la ciudad y el mismo método astronómico que usa la app. No se envió nada a ningún servidor.",
    "noscript": "El cálculo de los horarios necesita JavaScript. Todo lo demás en esta página funciona sin él.",
    "features_h2": "Qué hace la app",
    "f1_h3": "Las cinco oraciones y el sol que hay detrás",
    "f1_p": "Los horarios se calculan desde tus coordenadas con la geometría solar de siempre, así que valen estés donde estés. Una curva muestra el día entero de un vistazo, y una actividad en vivo lleva la cuenta atrás a la pantalla de bloqueo.",
    "f1_li1": "Varios métodos de cálculo, para coincidir con tu mezquita",
    "f1_li2": "Avisos de adhan, ajustables oración por oración",
    "f1_li3": "Dirección de la alquibla desde tu posición",
    "f1_alt": "La pantalla de horarios para La Meca: Fayr como próxima oración, la cuenta atrás y los horarios de hoy debajo.",
    "f2_h3": "Un tasbih que escucha",
    "f2_p": "Di el dhikr y el contador sigue. Reconoce las fórmulas en árabe y en transcripción, así no necesitas ni las manos ni la vista. Contar tocando sigue disponible cuando hablar no encaja.",
    "f2_li1": "Contar por voz es opcional; tocar siempre funciona",
    "f2_li2": "Objetivos por dhikr, con el historial del día",
    "f2_alt": "La pantalla del tasbih con Subhanallah en árabe y su traducción, y un rosario alrededor de un contador con objetivo 33.",
    "f3_h3": "Tu lugar en el Corán, guardado",
    "f3_p": "El avance se registra por yuz, sura y aleya, así que retomar la lectura no depende de acordarse. Las traducciones y recitaciones acompañan al texto.",
    "f3_alt": "La sura Al-Fatiha, con el texto árabe coloreado según el taywid, traducción al inglés y transcripción bajo cada aleya.",
    "f4_h3": "Mezquitas cerca de ti",
    "f4_p": "Un mapa de las mezquitas alrededor de tu posición, con búsqueda por nombre, para los días en que estás fuera y buscas oración en congregación.",
    "f4_alt": "Un mapa de La Meca con treinta mezquitas cercanas marcadas y un campo de búsqueda encima.",
    "f5_h3": "El zakat, calculado paso a paso",
    "f5_p": "El umbral del nisab en oro y en plata, actualizado con los precios de los metales, y partidas separadas para efectivo, oro, plata, activos del negocio y ganado.",
    "f5_alt": "La calculadora de zakat con los umbrales de nisab en oro y plata, y categorías de efectivo y ahorros, oro, plata y activos del negocio.",
    "f6_h3": "Una enciclopedia para leer",
    "f6_p": "Los profetas y sus relatos, una colección de hadices y un cuestionario para comprobar qué quedó. Escrita para leerse, no para ojearse.",
    "f6_alt": "El índice de la enciclopedia: los cinco pilares, la aqida, el fiqh, la guía, los profetas y la sira.",
    "priv_h2": "Qué sale de tu teléfono",
    "priv_lead": "Respuesta corta: tu ubicación no. La respuesta larga está en la {privacy_link}, escrita para leerse y no para aceptarse sin más.",
    "priv_link_text": "política de privacidad",
    "fact1_dt": "Ubicación",
    "fact1_dd": "Se usa en el dispositivo para los horarios y la alquibla. Una vez al mes la app contrasta las coordenadas con un servicio oficial de horarios para ajustarse al uso local, y pide a Apple el nombre de tu ciudad.",
    "fact2_dt": "Voz",
    "fact2_dd": "El reconocimiento del dhikr usa el reconocimiento de voz de Apple, que envía el audio a Apple para transcribirlo. Solo se activa mientras mantienes pulsado el botón de voz.",
    "fact3_dt": "Esta web",
    "fact3_dd": "Sin cookies, sin analítica, sin peticiones a terceros. Las tipografías se sirven desde este dominio.",
    "fact4_dt": "Tu cuenta",
    "fact4_dd": "Puedes {delete_link} sin escribir a nadie.",
    "fact4_link_text": "borrarla junto con sus datos",
    "cta_h2": "Pruébala en la próxima oración",
    "cta_p": "Gratis en ambas tiendas. Si no encaja con cómo rezas, bórrala; por nuestra parte no queda nada en ninguno de los dos casos.",
    "foot_tagline": "Una app de compañía islámica para iOS y Android, hecha por Harun Yaman.",
    "foot_app": "App",
    "foot_help": "Ayuda",
    "foot_legal": "Legal",
    "foot_contact": "Contacto",
    "foot_delete": "Borrar cuenta",
    "legal_privacy": "Privacidad",
    "legal_choices": "Opciones de privacidad",
    "legal_terms": "Condiciones",
    "legal_licences": "Licencias de código abierto",
    "lang_label": "Idioma",
}

S["tr"] = {
    "title": "Rowhni: iOS ve Android için namaz vakitleri, tesbih ve Kuran takibi",
    "description": "Rowhni beş vakit namazı cihazınızda hesaplar, zikri sesle sayar, Kuran'da kaldığınız yeri tutar, yakındaki camileri bulur ve zekâtı hesaplar. iOS ve Android'de ücretsiz.",
    "og_title": "Rowhni: telefonunuzda hesaplanan namaz vakitleri",
    "og_description": "Beş vakit namaz, konumunuzdan yola çıkarak cihazınızda hesaplanır. Ayrıca sesli tesbih, Kuran takibi, yakındaki camiler ve zekât hesaplayıcı.",
    "skip": "İçeriğe geç",
    "nav_label": "Ana gezinme",
    "nav_features": "Özellikler",
    "nav_privacy": "Gizlilik",
    "nav_support": "Destek",
    "theme_label": "Renk teması",
    "theme_system": "Sistemi izle",
    "theme_light": "Açık tema",
    "theme_dark": "Koyu tema",
    "get_app": "Uygulamayı al",
    "menu_open": "Menüyü aç",
    "menu_close": "Kapat",
    "h1": "Namaz vakitleri, telefonunuzda hesaplanır.",
    "lede": "Rowhni beş vakit namazı bulunduğunuz yere göre belirler ve hesabı cihazınızda yapar. Ayrıca zikri sesle sayar, Kuran'da kaldığınız yeri tutar, yakındaki camileri bulur ve zekâtı hesaplar.",
    "note": "Ücretsiz. iOS 18 veya üzeri ya da Android gerekir.",
    "store_download_on": "İndir:",
    "store_get_it_on": "Şuradan alın:",
    "times_caption": "Seçilen şehir için bugünün namaz vakitleri",
    "th_prayer": "Vakit",
    "th_time": "Saat",
    "next": "Sıradaki",
    "p_fajr": "İmsak",
    "p_sunrise": "Güneş",
    "p_dhuhr": "Öğle",
    "p_asr": "İkindi",
    "p_maghrib": "Akşam",
    "p_isha": "Yatsı",
    "city": "Şehir",
    "method": "Yöntem",
    "proof": "Tarayıcınız bu vakitleri şehrin koordinatlarından, uygulamanın kullandığı astronomik yöntemle hesapladı. Hiçbir sunucuya bir şey gönderilmedi.",
    "noscript": "Vakitlerin hesaplanması için JavaScript gerekir. Bu sayfadaki diğer her şey onsuz da çalışır.",
    "features_h2": "Uygulama ne yapıyor",
    "f1_h3": "Beş vakit ve arkasındaki güneş",
    "f1_p": "Vakitler, koordinatlarınızdan bilinen güneş geometrisiyle hesaplanır; bu yüzden nerede olursanız olun tutar. Güneşin yolu günün tamamını tek bakışta gösterir, Canlı Etkinlik ise sıradaki vakte kalan süreyi kilit ekranına taşır.",
    "f1_li1": "Caminizle uyuşması için farklı hesaplama yöntemleri",
    "f1_li2": "Her vakit için ayrı ayarlanabilen ezan bildirimleri",
    "f1_li3": "Bulunduğunuz yerden kıble yönü",
    "f1_alt": "Mekke için namaz vakitleri ekranı: sıradaki vakit İmsak, kalan süre ve altında bugünün vakitleri.",
    "f2_h3": "Dinleyen bir tesbih",
    "f2_p": "Zikri söyleyin, sayaç takip etsin. Uygulama kalıpları hem Arapça hem de latin harfli okunuşuyla tanır; elleriniz ve gözleriniz serbest kalır. Konuşmanın uygun olmadığı yerlerde dokunarak saymak yine mümkün.",
    "f2_li1": "Sesle saymak isteğe bağlı, dokunarak saymak her zaman çalışır",
    "f2_li2": "Her zikir için hedef ve günün geçmişi",
    "f2_alt": "Tesbih ekranında Subhanallah Arapça ve çevirisiyle, hedefi 33 olan sayacın çevresinde bir tesbih dizisi.",
    "f3_h3": "Kuran'da kaldığınız yer, kayıtlı",
    "f3_p": "İlerleme cüz, sure ve ayet olarak tutulur; kaldığınız yerden devam etmek hatırlamaya bağlı kalmaz. Mealler ve tilavetler metnin yanında durur.",
    "f3_alt": "Fatiha Suresi: Arapça metin tecvide göre renklendirilmiş, altında İngilizce meal ve okunuş.",
    "f4_h3": "Yakınınızdaki camiler",
    "f4_p": "Bulunduğunuz yerin çevresindeki camilerin haritası, adla aranabilir. Yolda olduğunuz ve cemaat aradığınız günler için.",
    "f4_alt": "Mekke haritası: yakındaki otuz cami işaretli, üstünde bir arama alanı.",
    "f5_h3": "Zekât, adım adım hesaplanır",
    "f5_p": "Altın ve gümüş üzerinden nisap eşiği, güncel maden fiyatlarıyla; nakit, altın, gümüş, ticaret malı ve hayvanlar için ayrı kalemler.",
    "f5_alt": "Zekât hesaplayıcısında altın ve gümüş nisap eşikleri ile nakit ve birikim, altın, gümüş ve ticaret malı kategorileri.",
    "f6_h3": "Okunacak bir ansiklopedi",
    "f6_p": "Peygamberler ve kıssaları, bir hadis derlemesi ve akılda kalanı ölçen bir test. Göz gezdirmek için değil, okumak için yazıldı.",
    "f6_alt": "Ansiklopedi içindekiler: beş şart, akide, fıkıh, rehberlik, peygamberler ve siyer.",
    "priv_h2": "Telefonunuzdan ne çıkıyor",
    "priv_lead": "Kısa cevap: konumunuz çıkmıyor. Uzun cevap, onaylanmak için değil okunmak için yazılmış {privacy_link} içinde.",
    "priv_link_text": "gizlilik politikasının",
    "fact1_dt": "Konum",
    "fact1_dd": "Vakitler ve kıble için cihazda kullanılır. Ayda bir kez uygulama, yerel uygulamaya uyum için koordinatları resmî bir vakit servisiyle karşılaştırır ve şehrinizin adını Apple'dan alır.",
    "fact2_dt": "Ses",
    "fact2_dd": "Zikir tanıma, Apple'ın ses tanımasını kullanır ve sesi yazıya dökmek için Apple'a gönderir. Yalnızca ses düğmesini basılı tuttuğunuz sürece çalışır.",
    "fact3_dt": "Bu site",
    "fact3_dd": "Çerez yok, analiz yok, üçüncü taraf isteği yok. Yazı tipleri bu alan adından gelir.",
    "fact4_dt": "Hesabınız",
    "fact4_dd": "Kimseye yazmadan {delete_link}.",
    "fact4_link_text": "hesabınızı ve verilerini silebilirsiniz",
    "cta_h2": "Sıradaki vakitte deneyin",
    "cta_p": "Her iki mağazada da ücretsiz. İbadetinize uymazsa silin; her iki durumda da bizde bir şey kalmaz.",
    "foot_tagline": "iOS ve Android için bir İslami yardımcı uygulama. Geliştiren: Harun Yaman.",
    "foot_app": "Uygulama",
    "foot_help": "Yardım",
    "foot_legal": "Hukuki",
    "foot_contact": "İletişim",
    "foot_delete": "Hesabı sil",
    "legal_privacy": "Gizlilik",
    "legal_choices": "Gizlilik tercihleri",
    "legal_terms": "Koşullar",
    "legal_licences": "Açık kaynak lisansları",
    "lang_label": "Dil",
}

S["ar"] = {
    "title": "روحني: مواقيت الصلاة والتسبيح ومتابعة القرآن لأجهزة iOS وأندرويد",
    "description": "يحسب تطبيق روحني الصلوات الخمس على جهازك، ويعدّ الذكر بالصوت، ويحفظ موضعك في القرآن، ويجد المساجد القريبة، ويحسب الزكاة. مجاني على iOS وأندرويد.",
    "og_title": "روحني: مواقيت الصلاة محسوبة على هاتفك",
    "og_description": "الصلوات الخمس محسوبة على جهازك انطلاقًا من موقعك. مع التسبيح الصوتي ومتابعة القرآن والمساجد القريبة وحاسبة الزكاة.",
    "skip": "تخطَّ إلى المحتوى",
    "nav_label": "التنقل الرئيسي",
    "nav_features": "المزايا",
    "nav_privacy": "الخصوصية",
    "nav_support": "الدعم",
    "theme_label": "سمة الألوان",
    "theme_system": "اتّباع النظام",
    "theme_light": "السمة الفاتحة",
    "theme_dark": "السمة الداكنة",
    "get_app": "حمّل التطبيق",
    "menu_open": "افتح القائمة",
    "menu_close": "إغلاق",
    "h1": "مواقيت الصلاة، محسوبة على هاتفك.",
    "lede": "يستخرج روحني الصلوات الخمس من موقعك، ويجري الحساب على جهازك. كما يعدّ الذكر بالصوت، ويحفظ موضعك في القرآن، ويجد المساجد القريبة، ويحسب الزكاة.",
    "note": "مجاني. يتطلب iOS 18 أو أحدث، أو أندرويد.",
    "store_download_on": "حمّله من",
    "store_get_it_on": "احصل عليه من",
    "times_caption": "مواقيت الصلاة اليوم للمدينة المختارة",
    "th_prayer": "الصلاة",
    "th_time": "الوقت",
    "next": "التالية",
    "p_fajr": "الفجر",
    "p_sunrise": "الشروق",
    "p_dhuhr": "الظهر",
    "p_asr": "العصر",
    "p_maghrib": "المغرب",
    "p_isha": "العشاء",
    "city": "المدينة",
    "method": "الطريقة",
    "proof": "حسب متصفحك هذه المواقيت من إحداثيات المدينة بالطريقة الفلكية نفسها التي يستخدمها التطبيق. لم يُرسل شيء إلى أي خادم.",
    "noscript": "يحتاج حساب المواقيت إلى جافاسكربت. أما بقية الصفحة فتعمل من دونه.",
    "features_h2": "ماذا يفعل التطبيق",
    "f1_h3": "الصلوات الخمس ومسار الشمس وراءها",
    "f1_p": "تُحسب المواقيت من إحداثياتك بالهندسة الشمسية المعتادة، فتصحّ أينما كنت. يعرض مسار الشمس اليوم كله في لمحة، ويضع النشاط المباشر الوقت المتبقي للصلاة القادمة على شاشة القفل.",
    "f1_li1": "عدة طرق للحساب لتوافق مسجدك",
    "f1_li2": "تنبيهات الأذان، تُضبط لكل صلاة على حدة",
    "f1_li3": "اتجاه القبلة من موقعك",
    "f1_alt": "شاشة المواقيت لمكة: الفجر هو الصلاة القادمة، والوقت المتبقي له، وتحته مواقيت اليوم.",
    "f2_h3": "مسبحة تُنصت",
    "f2_p": "قل الذكر ليتبعك العدّاد. يتعرّف التطبيق على الصيغ بالعربية وبالحروف اللاتينية، فتبقى يداك وعيناك حرّتين. ويظل العدّ باللمس متاحًا حين لا يناسب الكلام.",
    "f2_li1": "العدّ بالصوت اختياري، والعدّ باللمس متاح دائمًا",
    "f2_li2": "هدف لكل ذكر، مع سجل اليوم",
    "f2_alt": "شاشة المسبحة تعرض سبحان الله بالعربية مع ترجمتها، وحبات تحيط بعدّاد هدفه ٣٣.",
    "f3_h3": "موضعك من القرآن، محفوظ",
    "f3_p": "يُتابَع التقدّم بالجزء والسورة والآية، فلا يتوقف استئناف القراءة على التذكّر. وتقف الترجمات والتلاوات إلى جانب النص.",
    "f3_alt": "سورة الفاتحة، والنص العربي ملوّن بحسب التجويد، مع ترجمة إنجليزية ونقل صوتي تحت كل آية.",
    "f4_h3": "المساجد القريبة منك",
    "f4_p": "خريطة للمساجد حول موقعك مع بحث بالاسم، للأيام التي تكون فيها في مكان غير مألوف وتبحث عن الجماعة.",
    "f4_alt": "خريطة لمكة عليها ثلاثون مسجدًا قريبًا مُعلَّمة، وفوقها حقل بحث.",
    "f5_h3": "الزكاة، محسوبة خطوة بخطوة",
    "f5_p": "نصاب الذهب والفضة محدَّثًا بأسعار المعادن الجارية، مع بنود منفصلة للنقد والذهب والفضة وعروض التجارة والأنعام.",
    "f5_alt": "حاسبة الزكاة تعرض نصاب الذهب والفضة، وفئات النقد والمدخرات والذهب والفضة وعروض التجارة.",
    "f6_h3": "موسوعة للقراءة",
    "f6_p": "الأنبياء وقصصهم، ومجموعة من الأحاديث، واختبار لما ثبت في الذهن. كُتبت لتُقرأ لا لتُتصفّح.",
    "f6_alt": "فهرس الموسوعة: أركان الإسلام الخمسة والعقيدة والفقه والتوجيه والأنبياء والسيرة.",
    "priv_h2": "ما الذي يغادر هاتفك",
    "priv_lead": "الجواب المختصر: موقعك لا يغادره. والجواب المطوّل في {privacy_link}، وقد كُتبت لتُقرأ لا لتُوقَّع.",
    "priv_link_text": "سياسة الخصوصية",
    "fact1_dt": "الموقع",
    "fact1_dd": "يُستخدم على الجهاز لحساب المواقيت والقبلة. ومرة في الشهر يقارن التطبيق الإحداثيات بخدمة مواقيت رسمية ليوافق العُرف المحلي، ويطلب من آبل اسم مدينتك.",
    "fact2_dt": "الصوت",
    "fact2_dd": "يستعين التعرّف على الذكر بخدمة التعرّف على الكلام من آبل، فيُرسل الصوت إلى آبل لتفريغه نصًا. ولا يعمل إلا ما دمت ضاغطًا على زر الصوت.",
    "fact3_dt": "هذا الموقع",
    "fact3_dd": "بلا كوكيز ولا تحليلات ولا طلبات لأطراف أخرى. والخطوط تُقدَّم من هذا النطاق.",
    "fact4_dt": "حسابك",
    "fact4_dd": "يمكنك {delete_link} دون مراسلة أحد.",
    "fact4_link_text": "حذفه مع بياناته",
    "cta_h2": "جرّبه في الصلاة القادمة",
    "cta_p": "مجاني في المتجرين. وإن لم يناسب طريقتك في الصلاة فاحذفه؛ فلا يبقى لدينا شيء في الحالين.",
    "foot_tagline": "تطبيق إسلامي مرافق لأجهزة iOS وأندرويد، من تطوير هارون يامان.",
    "foot_app": "التطبيق",
    "foot_help": "المساعدة",
    "foot_legal": "قانوني",
    "foot_contact": "اتصل بنا",
    "foot_delete": "حذف الحساب",
    "legal_privacy": "الخصوصية",
    "legal_choices": "خيارات الخصوصية",
    "legal_terms": "الشروط",
    "legal_licences": "تراخيص المصادر المفتوحة",
    "lang_label": "اللغة",
}

S["ja"] = {
    "title": "Rowhni：iOS・Android向けの礼拝時刻、タスビーフ、クルアーン進捗",
    "description": "Rowhniは1日5回の礼拝時刻を端末上で計算し、ズィクルを音声で数え、クルアーンの読書位置を記録し、近くのモスクを探し、ザカートを計算します。iOSとAndroidで無料。",
    "og_title": "Rowhni：端末で計算する礼拝時刻",
    "og_description": "1日5回の礼拝時刻を、現在地から端末上で計算します。音声タスビーフ、クルアーンの進捗、近くのモスク、ザカート計算も。",
    "skip": "本文へ移動",
    "nav_label": "メインナビゲーション",
    "nav_features": "機能",
    "nav_privacy": "プライバシー",
    "nav_support": "サポート",
    "theme_label": "配色テーマ",
    "theme_system": "システムに合わせる",
    "theme_light": "ライトテーマ",
    "theme_dark": "ダークテーマ",
    "get_app": "アプリを入手",
    "menu_open": "メニューを開く",
    "menu_close": "閉じる",
    "h1": "礼拝時刻を、端末で計算する。",
    "lede": "Rowhniは現在地から1日5回の礼拝時刻を割り出し、計算は端末上で行います。音声でズィクルを数え、クルアーンの読書位置を保ち、近くのモスクを探し、ザカートも計算します。",
    "note": "無料。iOS 18以降、またはAndroidが必要です。",
    "store_download_on": "ダウンロード",
    "store_get_it_on": "入手先",
    "times_caption": "選択した都市の本日の礼拝時刻",
    "th_prayer": "礼拝",
    "th_time": "時刻",
    "next": "次",
    "p_fajr": "ファジュル",
    "p_sunrise": "日の出",
    "p_dhuhr": "ズフル",
    "p_asr": "アスル",
    "p_maghrib": "マグリブ",
    "p_isha": "イシャー",
    "city": "都市",
    "method": "計算方式",
    "proof": "これらの時刻は、都市の座標をもとに、アプリと同じ天文計算でブラウザが算出したものです。サーバーには何も送信されていません。",
    "noscript": "時刻の計算にはJavaScriptが必要です。このページの他の部分はJavaScriptなしでも動作します。",
    "features_h2": "できること",
    "f1_h3": "5つの礼拝と、その背後にある太陽",
    "f1_p": "時刻は現在地の座標から標準的な太陽の幾何計算で求めるため、どこにいても成り立ちます。太陽の軌道が1日全体をひと目で示し、ライブアクティビティが次の礼拝までの残り時間をロック画面に表示します。",
    "f1_li1": "複数の計算方式に対応し、通うモスクに合わせられます",
    "f1_li2": "礼拝ごとに設定できるアザーン通知",
    "f1_li3": "現在地からのキブラ方向",
    "f1_alt": "マッカの礼拝時刻画面。次の礼拝はファジュルで、そこまでの残り時間と本日の各時刻が並ぶ。",
    "f2_h3": "耳を傾けるタスビーフ",
    "f2_p": "ズィクルを唱えると、カウンターがついてきます。アラビア語でもラテン文字表記でも認識するため、手も目も画面から離せます。声を出しにくい場所では、タップで数えることもできます。",
    "f2_li1": "音声カウントは任意で、タップはいつでも使えます",
    "f2_li2": "ズィクルごとの目標と、その日の記録",
    "f2_alt": "タスビーフの画面。スブハーナッラーがアラビア語と訳で表示され、目標33のカウンターを数珠が囲む。",
    "f3_h3": "クルアーンの読書位置を保つ",
    "f3_p": "進捗はジュズウ、スーラ、アーヤ単位で記録されるため、続きから読むのに記憶は要りません。訳と朗誦は本文のそばに置かれています。",
    "f3_alt": "開端章。アラビア語本文はタジュウィードに従って色分けされ、各節の下に英訳と音写が置かれている。",
    "f4_h3": "近くのモスク",
    "f4_p": "現在地周辺のモスクを地図で表示し、名前で検索できます。不慣れな土地で集団礼拝を探すときのために。",
    "f4_alt": "マッカの地図。近隣のモスク30件が印で示され、上に検索欄がある。",
    "f5_h3": "ザカートを順を追って計算",
    "f5_p": "金と銀によるニサーブの基準額を、現在の地金価格で更新。現金、金、銀、事業資産、家畜をそれぞれ分けて入力できます。",
    "f5_alt": "ザカート計算画面。金と銀のニサーブ基準額と、現金・貯蓄、金、銀、事業資産の各項目が並ぶ。",
    "f6_h3": "読み通せる百科",
    "f6_p": "預言者たちとその物語、ハディース集、そして理解を確かめるクイズ。流し読みではなく、読むために書かれています。",
    "f6_alt": "百科の目次。五行、アキーダ、フィクフ、導き、預言者たち、シーラが並ぶ。",
    "priv_h2": "端末から出ていくもの",
    "priv_lead": "短い答え：位置情報は出ていきません。詳しくは{privacy_link}をご覧ください。同意させるためではなく、読まれるために書いています。",
    "priv_link_text": "プライバシーポリシー",
    "fact1_dt": "位置情報",
    "fact1_dd": "時刻とキブラの計算のため端末上で使います。月に一度、地域の慣行に合わせるため座標を公式の礼拝時刻サービスと照合し、都市名をAppleに問い合わせます。",
    "fact2_dt": "音声",
    "fact2_dd": "ズィクルの認識にはAppleの音声認識を使うため、文字起こしのために音声がAppleへ送信されます。音声ボタンを押している間だけ動作します。",
    "fact3_dt": "このサイト",
    "fact3_dd": "Cookieなし、アクセス解析なし、外部への通信なし。フォントもこのドメインから配信しています。",
    "fact4_dt": "アカウント",
    "fact4_dd": "問い合わせをしなくても、{delete_link}。",
    "fact4_link_text": "データごと削除できます",
    "cta_h2": "次の礼拝で試す",
    "cta_p": "どちらのストアでも無料です。礼拝の習慣に合わなければ削除してください。いずれの場合も、こちらに何かが残ることはありません。",
    "foot_tagline": "iOSとAndroid向けのイスラーム生活支援アプリ。開発：ハルン・ヤマン。",
    "foot_app": "アプリ",
    "foot_help": "ヘルプ",
    "foot_legal": "法的事項",
    "foot_contact": "お問い合わせ",
    "foot_delete": "アカウント削除",
    "legal_privacy": "プライバシー",
    "legal_choices": "プライバシー設定",
    "legal_terms": "利用規約",
    "legal_licences": "オープンソースライセンス",
    "lang_label": "言語",
}

S["id"] = {
    "title": "Rowhni: jadwal salat, tasbih, dan progres Al-Qur'an untuk iOS dan Android",
    "description": "Rowhni menghitung lima waktu salat di perangkat Anda, menghitung zikir lewat suara, menyimpan posisi bacaan Al-Qur'an, menemukan masjid terdekat, dan menghitung zakat. Gratis di iOS dan Android.",
    "og_title": "Rowhni: jadwal salat yang dihitung di ponsel Anda",
    "og_description": "Lima waktu salat, dihitung di perangkat Anda dari lokasi Anda. Ditambah tasbih suara, progres Al-Qur'an, masjid terdekat, dan kalkulator zakat.",
    "skip": "Lompat ke konten",
    "nav_label": "Navigasi utama",
    "nav_features": "Fitur",
    "nav_privacy": "Privasi",
    "nav_support": "Bantuan",
    "theme_label": "Tema warna",
    "theme_system": "Ikuti sistem",
    "theme_light": "Tema terang",
    "theme_dark": "Tema gelap",
    "get_app": "Unduh aplikasi",
    "menu_open": "Buka menu",
    "menu_close": "Tutup",
    "h1": "Jadwal salat, dihitung di ponsel Anda.",
    "lede": "Rowhni menghitung lima waktu salat dari tempat Anda berada, dan perhitungannya dilakukan di perangkat Anda. Aplikasi ini juga menghitung zikir lewat suara, menyimpan posisi bacaan Al-Qur'an, menemukan masjid terdekat, dan menghitung zakat.",
    "note": "Gratis. Perlu iOS 18 atau lebih baru, atau Android.",
    "store_download_on": "Unduh di",
    "store_get_it_on": "Dapatkan di",
    "times_caption": "Jadwal salat hari ini untuk kota yang dipilih",
    "th_prayer": "Salat",
    "th_time": "Waktu",
    "next": "Berikutnya",
    "p_fajr": "Subuh",
    "p_sunrise": "Terbit",
    "p_dhuhr": "Zuhur",
    "p_asr": "Asar",
    "p_maghrib": "Magrib",
    "p_isha": "Isya",
    "city": "Kota",
    "method": "Metode",
    "proof": "Peramban Anda menghitung waktu-waktu ini dari koordinat kota dengan metode astronomi yang sama seperti aplikasinya. Tidak ada yang dikirim ke server.",
    "noscript": "Perhitungan waktu memerlukan JavaScript. Bagian lain halaman ini tetap berfungsi tanpanya.",
    "features_h2": "Apa yang dilakukannya",
    "f1_h3": "Lima waktu salat, dan matahari di baliknya",
    "f1_p": "Waktu dihitung dari koordinat Anda memakai geometri matahari yang lazim, sehingga tetap tepat di mana pun Anda berada. Lintasan matahari menampilkan satu hari penuh sekaligus, dan Live Activity menaruh hitung mundur ke salat berikutnya di layar kunci.",
    "f1_li1": "Beberapa metode perhitungan, agar cocok dengan masjid Anda",
    "f1_li2": "Notifikasi azan yang bisa diatur per waktu salat",
    "f1_li3": "Arah kiblat dari posisi Anda",
    "f1_alt": "Layar jadwal salat untuk Mekah: Subuh sebagai salat berikutnya, hitung mundurnya, dan jadwal hari ini di bawahnya.",
    "f2_h3": "Tasbih yang mendengarkan",
    "f2_p": "Ucapkan zikirnya, penghitung mengikuti. Aplikasi mengenali lafalnya dalam bahasa Arab maupun transliterasi, sehingga tangan dan mata Anda tetap bebas. Menghitung dengan sentuhan tetap tersedia bila bersuara kurang pas.",
    "f2_li1": "Menghitung dengan suara bersifat opsional; sentuhan selalu bisa",
    "f2_li2": "Target untuk tiap zikir, lengkap dengan riwayat hari itu",
    "f2_alt": "Layar tasbih menampilkan Subhanallah dalam bahasa Arab beserta artinya, dan untaian butir mengelilingi penghitung dengan target 33.",
    "f3_h3": "Posisi bacaan Al-Qur'an Anda, tersimpan",
    "f3_p": "Progres dicatat per juz, surah, dan ayat, jadi melanjutkan bacaan tidak bergantung pada ingatan. Terjemahan dan murottal tersedia di samping teksnya.",
    "f3_alt": "Surah Al-Fatihah, teks Arab diwarnai menurut tajwid, dengan terjemahan Inggris dan transliterasi di bawah tiap ayat.",
    "f4_h3": "Masjid di dekat Anda",
    "f4_p": "Peta masjid di sekitar posisi Anda, bisa dicari berdasarkan nama, untuk saat Anda berada di tempat asing dan mencari jemaah.",
    "f4_alt": "Peta Mekah dengan tiga puluh masjid terdekat yang ditandai, dan kolom pencarian di atasnya.",
    "f5_h3": "Zakat, dihitung langkah demi langkah",
    "f5_p": "Ambang nisab dalam emas dan perak, diperbarui dengan harga logam terkini, serta pos terpisah untuk kas, emas, perak, aset usaha, dan hewan ternak.",
    "f5_alt": "Kalkulator zakat menampilkan ambang nisab emas dan perak, dengan kategori kas dan tabungan, emas, perak, serta aset usaha.",
    "f6_h3": "Ensiklopedia untuk dibaca",
    "f6_p": "Para nabi dan kisahnya, kumpulan hadis, dan kuis untuk menguji apa yang tersimpan. Ditulis untuk dibaca, bukan dilewati sekilas.",
    "f6_alt": "Daftar isi ensiklopedia: rukun Islam, akidah, fikih, tuntunan, para nabi, dan sirah.",
    "priv_h2": "Apa yang keluar dari ponsel Anda",
    "priv_lead": "Jawaban singkatnya: lokasi Anda tidak. Jawaban panjangnya ada di {privacy_link}, yang ditulis untuk dibaca, bukan sekadar disetujui.",
    "priv_link_text": "kebijakan privasi",
    "fact1_dt": "Lokasi",
    "fact1_dd": "Dipakai di perangkat untuk menghitung waktu dan arah kiblat. Sebulan sekali aplikasi mencocokkan koordinat dengan layanan jadwal salat resmi agar sesuai kebiasaan setempat, dan menanyakan nama kota Anda ke Apple.",
    "fact2_dt": "Suara",
    "fact2_dd": "Pengenalan zikir memakai pengenalan suara Apple, yang mengirim audio ke Apple untuk ditranskripsikan. Ini hanya berjalan selama Anda menahan tombol suara.",
    "fact3_dt": "Situs ini",
    "fact3_dd": "Tanpa kuki, tanpa analitik, tanpa permintaan ke pihak ketiga. Fontnya pun dilayani dari domain ini.",
    "fact4_dt": "Akun Anda",
    "fact4_dd": "Anda bisa {delete_link} tanpa perlu menghubungi siapa pun.",
    "fact4_link_text": "menghapusnya beserta datanya",
    "cta_h2": "Coba pada salat berikutnya",
    "cta_p": "Gratis di kedua toko. Kalau tidak cocok dengan cara Anda beribadah, hapus saja; bagaimanapun tidak ada yang tertinggal di sisi kami.",
    "foot_tagline": "Aplikasi pendamping islami untuk iOS dan Android, dibuat oleh Harun Yaman.",
    "foot_app": "Aplikasi",
    "foot_help": "Bantuan",
    "foot_legal": "Hukum",
    "foot_contact": "Kontak",
    "foot_delete": "Hapus akun",
    "legal_privacy": "Privasi",
    "legal_choices": "Pilihan privasi",
    "legal_terms": "Ketentuan",
    "legal_licences": "Lisensi sumber terbuka",
    "lang_label": "Bahasa",
}

S["ms"] = {
    "title": "Rowhni: waktu solat, tasbih dan kemajuan al-Quran untuk iOS dan Android",
    "description": "Rowhni mengira lima waktu solat pada peranti anda, mengira zikir melalui suara, menyimpan tempat bacaan al-Quran, mencari masjid berdekatan dan mengira zakat. Percuma di iOS dan Android.",
    "og_title": "Rowhni: waktu solat yang dikira pada telefon anda",
    "og_description": "Lima waktu solat, dikira pada peranti anda daripada lokasi anda. Serta tasbih suara, kemajuan al-Quran, masjid berdekatan dan kalkulator zakat.",
    "skip": "Langkau ke kandungan",
    "nav_label": "Navigasi utama",
    "nav_features": "Ciri",
    "nav_privacy": "Privasi",
    "nav_support": "Sokongan",
    "theme_label": "Tema warna",
    "theme_system": "Ikut sistem",
    "theme_light": "Tema cerah",
    "theme_dark": "Tema gelap",
    "get_app": "Dapatkan apl",
    "menu_open": "Buka menu",
    "menu_close": "Tutup",
    "h1": "Waktu solat, dikira pada telefon anda.",
    "lede": "Rowhni mengira lima waktu solat daripada tempat anda berada, dan pengiraannya dilakukan pada peranti anda. Apl ini turut mengira zikir melalui suara, menyimpan tempat bacaan al-Quran, mencari masjid berdekatan dan mengira zakat.",
    "note": "Percuma. Memerlukan iOS 18 atau lebih baharu, atau Android.",
    "store_download_on": "Muat turun di",
    "store_get_it_on": "Dapatkan di",
    "times_caption": "Waktu solat hari ini bagi bandar yang dipilih",
    "th_prayer": "Solat",
    "th_time": "Waktu",
    "next": "Seterusnya",
    "p_fajr": "Subuh",
    "p_sunrise": "Syuruk",
    "p_dhuhr": "Zohor",
    "p_asr": "Asar",
    "p_maghrib": "Maghrib",
    "p_isha": "Isyak",
    "city": "Bandar",
    "method": "Kaedah",
    "proof": "Pelayar anda mengira waktu ini daripada koordinat bandar dengan kaedah astronomi yang sama seperti apl. Tiada apa-apa dihantar ke pelayan.",
    "noscript": "Pengiraan waktu memerlukan JavaScript. Selebihnya pada halaman ini berfungsi tanpanya.",
    "features_h2": "Apa yang apl ini buat",
    "f1_h3": "Lima waktu solat, dan matahari di sebaliknya",
    "f1_p": "Waktu dikira daripada koordinat anda menggunakan geometri matahari yang biasa, jadi ia tepat di mana sahaja anda berada. Laluan matahari menunjukkan sepanjang hari sekali pandang, dan Live Activity meletakkan kiraan detik ke solat berikutnya pada skrin kunci.",
    "f1_li1": "Beberapa kaedah pengiraan, supaya sepadan dengan masjid anda",
    "f1_li2": "Pemberitahuan azan yang boleh ditetapkan bagi setiap waktu",
    "f1_li3": "Arah kiblat dari kedudukan anda",
    "f1_alt": "Skrin waktu solat bagi Mekah: Subuh sebagai solat berikutnya, kiraan detik kepadanya, dan waktu hari ini di bawahnya.",
    "f2_h3": "Tasbih yang mendengar",
    "f2_p": "Sebut zikirnya, pengira akan mengikut. Apl ini mengenali lafaz dalam bahasa Arab dan dalam transliterasi, jadi tangan dan mata anda kekal bebas. Mengira dengan sentuhan masih ada apabila bersuara kurang sesuai.",
    "f2_li1": "Mengira dengan suara bersifat pilihan; sentuhan sentiasa berfungsi",
    "f2_li2": "Sasaran bagi setiap zikir, dengan rekod hari itu",
    "f2_alt": "Skrin tasbih memaparkan Subhanallah dalam bahasa Arab beserta terjemahannya, dan untaian butir mengelilingi pengira bersasaran 33.",
    "f3_h3": "Tempat bacaan al-Quran anda, tersimpan",
    "f3_p": "Kemajuan direkod mengikut juzuk, surah dan ayat, jadi menyambung bacaan tidak bergantung pada ingatan. Terjemahan dan bacaan ada di sisi teksnya.",
    "f3_alt": "Surah Al-Fatihah, teks Arab diwarnakan mengikut tajwid, dengan terjemahan Inggeris dan transliterasi di bawah setiap ayat.",
    "f4_h3": "Masjid berhampiran anda",
    "f4_p": "Peta masjid di sekitar kedudukan anda, boleh dicari mengikut nama, untuk waktu anda berada di tempat asing dan mencari jemaah.",
    "f4_alt": "Peta Mekah dengan tiga puluh masjid berhampiran ditanda, dan medan carian di atasnya.",
    "f5_h3": "Zakat, dikira langkah demi langkah",
    "f5_p": "Nilai nisab dalam emas dan perak, dikemas kini dengan harga logam semasa, serta butiran berasingan bagi tunai, emas, perak, aset perniagaan dan ternakan.",
    "f5_alt": "Kalkulator zakat memaparkan nilai nisab emas dan perak, dengan kategori tunai dan simpanan, emas, perak serta aset perniagaan.",
    "f6_h3": "Ensiklopedia untuk dibaca",
    "f6_p": "Para nabi dan kisah mereka, koleksi hadis, dan kuiz untuk menguji apa yang tinggal. Ditulis untuk dibaca, bukan diimbas sekilas.",
    "f6_alt": "Kandungan ensiklopedia: rukun Islam, akidah, fiqh, panduan, para nabi dan sirah.",
    "priv_h2": "Apa yang keluar dari telefon anda",
    "priv_lead": "Jawapan ringkas: lokasi anda tidak. Jawapan panjangnya ada dalam {privacy_link}, yang ditulis untuk dibaca dan bukan sekadar dipersetujui.",
    "priv_link_text": "dasar privasi",
    "fact1_dt": "Lokasi",
    "fact1_dd": "Digunakan pada peranti untuk mengira waktu dan kiblat. Sebulan sekali apl membandingkan koordinat dengan perkhidmatan waktu solat rasmi agar menepati kebiasaan setempat, dan meminta nama bandar anda daripada Apple.",
    "fact2_dt": "Suara",
    "fact2_dd": "Pengecaman zikir menggunakan pengecaman suara Apple, yang menghantar audio kepada Apple untuk ditranskripsi. Ia hanya berjalan selagi anda menahan butang suara.",
    "fact3_dt": "Laman ini",
    "fact3_dd": "Tiada kuki, tiada analitik, tiada permintaan pihak ketiga. Fon pun disajikan dari domain ini.",
    "fact4_dt": "Akaun anda",
    "fact4_dd": "Anda boleh {delete_link} tanpa perlu menghubungi sesiapa.",
    "fact4_link_text": "memadamnya bersama datanya",
    "cta_h2": "Cuba pada solat berikutnya",
    "cta_p": "Percuma di kedua-dua gedung. Jika ia tidak sesuai dengan cara anda beribadah, padamkannya; apa pun keadaannya, tiada apa yang tinggal di pihak kami.",
    "foot_tagline": "Apl teman Islami untuk iOS dan Android, dibina oleh Harun Yaman.",
    "foot_app": "Apl",
    "foot_help": "Bantuan",
    "foot_legal": "Perundangan",
    "foot_contact": "Hubungi",
    "foot_delete": "Padam akaun",
    "legal_privacy": "Privasi",
    "legal_choices": "Pilihan privasi",
    "legal_terms": "Terma",
    "legal_licences": "Lesen sumber terbuka",
    "lang_label": "Bahasa",
}
